### ISSUE TITLE
Cannot access classes_ member in Classifier

### ISSUE THREAD

**Issue by kazuki** [jubatus/embedded-jubatus-python#37]
in embedded-jubatus 1.0.4
```
AttributeError: 'embedded_jubatus.Classifier' object has no attribute 'classes_'
```
but embedded-jubatus 1.0.3 can access classes_ attribute.

**Comment by kmaehashi** [comment]
Fixed via #38 

This issue occurred because `Classifier` is changed from Python class to Cython cdef class in 1.0.4 so fields became invisible from Python world.
Refs:
https://github.com/jubatus/embedded-jubatus-python/pull/33/files#diff-5fa7fc715cd2eb41481e0a79747e0c5dL148
https://github.com/jubatus/embedded-jubatus-python/pull/33/files#diff-7493459567ce0900d1cacfccbc565bd5L1
